[package]
name = "fastboot"
version = "0.1.0"
authors = ["rostyslav <rkhudolii@airtame.com>"]
publish = false

[lib]
name = "fastboot"

[dev-dependencies]
getopts = "*"

[dev-dependencies.usbio]
path = "usbio"